### ISSUE TITLE
Error on Linux 

### ISSUE THREAD

**Issue by riccardovalente** [Maboroshy/Note-Station-to-markdown#1]
any suggestions? 

```
Traceback (most recent call last):
  File "nsx2md.py", line 33, in <module>
    config_data = json.loads(nsx.read('config.json'))
  File "/usr/lib64/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Notestation 2.4.3-0810
Python 2.7.5
pandoc 1.12.3.1
RHEL 7.3

**Comment by Maboroshy** [comment]
The script requires Python 3+, it won't work with Python 2.7.5, sorry.

**Comment by riccardovalente** [comment]
Sorry my misktake - that's the actual result with Python 3.4, I just pasted the wrong info. Python 2.7 can't even find pandoc.

**Comment by Maboroshy** [comment]
I'll try to reproduce your issue.

**Comment by Maboroshy** [comment]
Looks like I've used Python 3.6 feature for json part. I'll fix this and make some test for 3.4 and above.

**Comment by Maboroshy** [comment]
I've updated the script file. Please test the new version.

**Comment by riccardovalente** [comment]
Different error:

```
$ python3 nsx2md.py 
Converting notebook "Home"
Traceback (most recent call last):
  File "nsx2md.py", line 96, in <module>
    md_note.write(content)
NameError: name 'content' is not defined
```

**Comment by Maboroshy** [comment]
Try the new version please.

**Comment by riccardovalente** [comment]
Thanks for the update. New output:

```
python3 nsx2md.py 
Converting notebook "Home"
pandoc: unrecognized option `--wrap=none'
Try pandoc --help for more information.
pandoc: unrecognized option `--wrap=none'
Try pandoc --help for more information.
pandoc: unrecognized option `--wrap=none'
Try pandoc --help for more information.
pandoc: unrecognized option `--wrap=none'
Try pandoc --help for more information.
Traceback (most recent call last):
  File "nsx2md.py", line 89, in <module>
    if note_data['tag'] or attachment_list:
KeyError: 'tag'
```

Should I try a different version of pandoc? Using 1.12 atm.

**Comment by Maboroshy** [comment]
`--wrap` option was implemented in pandoc 1.16. I'll check if there's a workaround for previous versions. Personally I can't stand "wrapped" text, even if it's markdown.

You can remove text `'--wrap=none'` from the script manually for now. Line 61 would look like `],`

**Comment by Maboroshy** [comment]
Try changing '--wrap=none' to `--no-wrap` in line 61.

**Comment by riccardovalente** [comment]
Yes that works (I'm quite happy with no-wrap), however I still get the error in line 89 as above

**Comment by Maboroshy** [comment]
Test the new version, please. `'--no-wrap'` fix is also implemented there.
Looks like my test data set was far too thin.

**Comment by riccardovalente** [comment]
Much better, now the issue is with notes which have '/' in the title. I can work around that before exporting though.

**Comment by Maboroshy** [comment]
What would you prefer to do with the title? Replace with `-` or some other symbol?

**Comment by riccardovalente** [comment]
I'm not sure if replacing is a good idea; it would be ok for dates etc but URLs would be badly affected and would need to be corrected manually anyway. Escaping, perhaps? / -> \/ or similar? Sorry I don't use Python

**Comment by Maboroshy** [comment]
It has not much to do with Python, but with OS. I've tried `touch test\/test` on Linux with no success. So I'm afraid escaping might not work. 

You say URLs can go wrong, but we're talking about file names. Do you really need a working URL in a file name? I can implement inserting original title to note text, so you won't lost it.

**Comment by riccardovalente** [comment]
Sure, the reference to Python was me wondering whether there was an escaping library or similar. No tbh I don't need URL in titles, I just happened to have a note that did. Quite happy to replace all slashes with hyphens; how about a warning when that happens, so one can review after the conversion?

**Comment by Maboroshy** [comment]
Note content won't be altered, only the file name. I'll put something tomorrow. Warnings included.

**Comment by Maboroshy** [comment]
Check the new version please. It makes filenames safe, inserts title into note text (can be disabled) and differs pandoc versions now.

**Comment by riccardovalente** [comment]
Fabulous - all working now, thousands of notes converted with no issues. Thanks very much for this, and your patience!
