### ISSUE TITLE
Crash when trash is not empty

### ISSUE THREAD

**Issue by AMTQ** [Maboroshy/Note-Station-to-markdown#10]
When the trash is not empty, it gives me this error on line 132:
parent_notebook = notebook_id_to_path_index[parent_notebook_id]

KeyError: '1027_#00000000'

Emptying the trash and re-exporting the notebook solves the issue.

**Comment by Maboroshy** [comment]
I can't reproduce it. I get nothing from trash exported to .nsx. I've put an exception handling though.
