### ISSUE TITLE
Really long titles crash

### ISSUE THREAD

**Issue by AMTQ** [Maboroshy/Note-Station-to-markdown#11]
I have one note with a title length of 414 characters, this causes a crash on line 223 md_file_path.write_text(content, 'utf-8').

Shortening the title in the sanitise_path_string(path_str) method resolves the issue.:
```
    if truncate_title and len(path_str) > truncate_title_chars:
        path_str = path_str[:truncate_title_chars]
```
But this requires adding new settings as for example:
```
truncate_title = True # Catch problems with titles that are too long
truncate_title_chars = 200 # Do not allow more than X characters for a title
```

**Comment by Maboroshy** [comment]
Note title limited to 240 characters in latest version, most file systems impose 255 char limit.
