### ISSUE TITLE
List notes that are not converted

### ISSUE THREAD

**Issue by jmooo** [Maboroshy/Note-Station-to-markdown#16]
After the script completes I get the message:

> Converted 16 notebooks and 371 out of 384 notes. Press Enter to quit...

Is it possible to get more info about what was _not_ converted? Thanks!

**Comment by Maboroshy** [comment]
Will do.

**Comment by jmooo** [comment]
Haha, you're awesome (and fast). Let me know if you want me to test anything from a feature branch or something!

**Comment by Maboroshy** [comment]
I've uploaded new version to master branch. Please, test.

**Comment by jmooo** [comment]
Ahh it looks like all 13 it failed to convert were in the DS Note "Recycle Bin". I emptied the bin, re-exported, and ran the script again and all notes converted. Is there something special about the .nsx format for the Recycle Bin?

Also it looks like the 20s wait for pandoc got reverted to 5s in that latest push. Thank you!!

**Comment by Maboroshy** [comment]
I can't test recycle bin notes. For some reason I can't get notes from recycle bin exported to .nsx by Note Station on my old DS. Notes from recycle bin don't belong to any notebook, so the script skips them and consider as failed to convert.

My bad for 20s. Will fix.

**Comment by jmooo** [comment]
I made a Test Notebook with 2 notes, then I deleted 1 of them. When I export the Test Notebook it looks like macOS Desktop DS Note _also_ exports my Recycle Bin along with the Test Notebook. Not sure why, I didn't actually select to export the Recycle Bin (there is no option to export it, regardless)

If you'd like to take a look at the Test Notebook export with  1 deleted note and 1 not-deleted note I put it here: https://www.dropbox.com/s/x32fbljjdb0fxew/maboroshy-test-notebook-export.nsx?dl=0

**Comment by Maboroshy** [comment]
Thanks for that .nsx. I see that id format for notes and notebooks looks different to mine. Deleted notes has a specific parent id that looks like a reserved one for recycle bin.

Looks like .nsx export feature use different code on different Note Station clients.

I'll implement recycle bin handling based on your .nsx, but it's a shot in the dark for me. There's no recycle bin export on DS's embedded Note Station client I use for testing.

**Comment by Maboroshy** [comment]
I've implemented recycle bin handling that can handle your test file.
