### ISSUE TITLE
Syntax Error: invalid syntax

### ISSUE THREAD

**Issue by truthsword** [Maboroshy/Note-Station-to-markdown#17]
I'm sure this is a blatant noobie error, but ... I get...

**F:\nsx2md>python nsx2md.py
  File "nsx2md.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax**

I'm running Win10x64 with Python37 (x64) and lastest Pandoc (x64). Both Python and Pandoc are in PATH. I tried moving the py script and the nsx file into the Python folder, but same message.

**Comment by Maboroshy** [comment]
The only thing I can think of to cause something like this is line breaks incompatibility. I have encountered it while testing the script in Windows 7.

I've changed line breaks to Windows native. Please test the new version.

**Comment by truthsword** [comment]
I'm all good now. Thanks!

**Comment by truthsword** [comment]
I'm all good now. Thanks!

**Comment by mateMathieu** [comment]
Hi @Maboroshy , I am having the same issue on Linux.

Installed dependencies, made it executable and rand the script as documented:
python nsx2md.py test.nsx
File "nsx2md.py", line 1
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version:   ##5.12.8
Kernel Version: 5.4.0-38-generic
OS Type: 64-bit

Thank you

**Comment by Maboroshy** [comment]
Try `python3 nsx2md.py test.nsx`.

**Comment by mateMathieu** [comment]
Hi, thanks for the tip, but I tried and it did not work.

**Comment by mateMathieu** [comment]
Tried with python3.8 nsx2md.py, but same result. The dependencies you specifies are met. I really want to get away from this locked-down situation. Can you help me please?

**Comment by Maboroshy** [comment]
I'll look into this.

**Comment by Maboroshy** [comment]
I still can't reproduce the issue on a Kubuntu VM. Could you delete the first two lines of `nsx2md.py` (the `#!/` one and empty) and tell me what changes.

**Comment by mateMathieu** [comment]
Hi,

This is the begining of the script file:





<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

Which lines should I delete?
Thanks

**Comment by Maboroshy** [comment]
It seems to me that you saved a github web page with the script rather than the script itself. Try downloading the code as a zip (github has a button for that) and using the script file from that zip.

**Comment by mateMathieu** [comment]
Yes you are right. It does work fine.
Do you know why the file from the repo and from the zip are different?

**Comment by Maboroshy** [comment]
Zip is the exact content of the repo. I guess you've downloaded the script by browser's command "Save target as..." or something like that. At GitHub that leads to html and that can cause a surprise like you've had.
