### ISSUE TITLE
 TypeError: '<' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by cyorps** [Maboroshy/Note-Station-to-markdown#18]
Hi Maboroshy,

when run this script in Windows 10 and Python 3.7.3, I get following error output:

Found pandoc exe 2.7.3
Traceback (most recent call last):
  File "nsx2md.py", line 66, in <module>
    if distutils.version.LooseVersion(pandoc_ver) < distutils.version.LooseVersion('1.16'):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\lib\distutils\version.py", line 52, in __lt__
    c = self._cmp(other)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1008.0_x64__qbz5n2kfra8p0\lib\distutils\version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'

Can I do something to fix it or is it a problem of the code?

**Comment by Maboroshy** [comment]
That's something new. Can't reproduce that on my Manjaro Linux and Windows 7. 
I'll find some workaround to make it work.

**Comment by Maboroshy** [comment]
Meanwhile you can replace lines 60-75 with 
``` python
pandoc_args = ['pandoc', '-f', 'html', '-t', 'markdown_strict+pipe_tables-raw_html',
               '--wrap=none', '--atx-headers', '-o',
               pandoc_output_file.name, pandoc_input_file.name]
```
That will make the script work.

**Comment by Maboroshy** [comment]
Looks like the script gets an extra space in pandoc version output on your system. I've added some extra safety.
Please, test the new version.

**Comment by Juvls** [comment]
Hi, I still have this issue with latest script version on Windows 10, python 3.7 and pandoc 2.7.3 both installed with chocolatey.

`C:\Users\Julien\Documents\notes>nsx2md.py
Found pandoc exe 2.7.3
Traceback (most recent call last):
  File "C:\Users\Julien\Documents\notes\nsx2md.py", line 66, in <module>
    if distutils.version.LooseVersion(pandoc_ver) < distutils.version.LooseVersion('1.16'):
  File "C:\Python37\lib\distutils\version.py", line 52, in __lt__
    c = self._cmp(other)
  File "C:\Python37\lib\distutils\version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: '<' not supported between instances of 'str' and 'int'`

**Comment by Maboroshy** [comment]
Thanks for reporting. I'll prepare a Windows 10 virtual machine to make a proper fix.

**Comment by Maboroshy** [comment]
I can't reproduce the issue on my Windows 10 VM. But I've put whole pandoc version detection to "try" clause so defaults would be used on any exceptions. Little hacky but should resolve the issue.

**Comment by Juvls** [comment]
Yes it works with your change, thanks :)

**Comment by Maboroshy** [comment]
Thank you for testing.
