### ISSUE TITLE
Convert to HTML?

### ISSUE THREAD

**Issue by cfenz** [Maboroshy/Note-Station-to-markdown#19]
Is there any chance to add functionality to convert NSX to HTML for subsequent importing into other applications (e.g., OneNote)?

**Comment by Maboroshy** [comment]
Note station stores notes in html. So it should be possible and even easier than markdown. 
But I'm not sure about images/attachments paths. Need to check this.

**Comment by Maboroshy** [comment]
I'm a little stuck with your request. The script has a very basic procedure architecture to do what it's meant to do. I haven't found a good way to implement html conversion with a current architecture. And I don't want to refactor the script because it's good enough to do declared task.

So I'm considering writing a special script for html conversion as stand-alone project. I hope to write something on a weekend.

**Comment by cfenz** [comment]
That would be super cool. Thanks for digging in on this.

**Comment by Maboroshy** [comment]
Check https://github.com/Maboroshy/Note-Station-to-html
It's still work in progress so there may be some bugs. This one doesn't require pandoc, only Python.

**Comment by cfenz** [comment]
Hey there, I finally had the opportunity to try this out.

It seems to work reasonably well in converting NSX to HTML.  The only thing
that doesn't work quite right - but maybe this is a problem with the native
NSX format - is the images.  It strips the images in the original HTML into
a folder called "media" and puts links at the top of the HTML to
"attachments", rather than showing them in-line as with the original web
page.  Is this fixable?

**Comment by Maboroshy** [comment]
Yes, it's a bug. I will look into it.

**Comment by Maboroshy** [comment]
I can't reproduce the images issue. Could you upload an example of converted html with broken inline images. Maybe some test note.

**Comment by cfenz** [comment]
Were you able to reproduce?  If not, no problem I recognize this is not
paid work for you!

**Comment by Maboroshy** [comment]
As I've posted earlier I wasn't able to reproduce the issue. Could you upload an nsx with a test note that gets broken in-line images after conversion?

**Comment by cfenz** [comment]
I attempted to upload into the "Issues" section, please advise if you
received.

**Comment by Maboroshy** [comment]
Got. I'll look into it.

**Comment by Maboroshy** [comment]
I've uploaded the new version that should fix the issue. Please, test and let me know if it works.
