### ISSUE TITLE
tables containing block elements will be dropped completely from Markdown output

### ISSUE THREAD

**Issue by jgreely** [Maboroshy/Note-Station-to-markdown#27]
Unless you use the 'multiline_tables' extension to pandoc, any table containing a block element such as a DIV will be completely replaced by the string "[TABLE]", potentially causing significant data loss. Note Station apparently inserts all kinds of cruft into its tables.

**Comment by Maboroshy** [comment]
Thanks, I'll look into this. If `multiline_tables` gives no side effects I'll just add it to pandoc options.

**Comment by jgreely** [comment]
The formatting is a mess, but at least the data is present; it might be better to call out the failures in the output, and make it an option to retry for just the ones that need it (in my case, only 5 of 200+ notes lost data or references to attachments).

**Comment by Maboroshy** [comment]
I've implemented unconverted tables warning and moved pandoc options up for easy tweaking.
