### ISSUE TITLE
Cannot see Pictures after Export with your Script

### ISSUE THREAD

**Issue by MichaelLepori** [Maboroshy/Note-Station-to-markdown#28]
Hi,
first of all, thank you for your great job.
I have this issue with Pictures.
I exported all my DS Notes and then imported in Obsidian.
I can't see the pictures, when the format is like this after the export: ![](file://media/15101598275384230.png)
But if I try to link it like this ![[15101598275384230.png]], it works.
Do you habe any suggestion?
Thank you very much!
Michael

**Comment by Maboroshy** [comment]
Obsidian has it's own custom syntax for images, which is ` ![[15101598275384230.png]]`. The script is aimed to make a markdown spec links. You may have to adapt the output to the specific app.
