### ISSUE TITLE
It seems the image is not displaying correctly, even though the image file can be located

### ISSUE THREAD

**Issue by JackyWay** [Maboroshy/Note-Station-to-markdown#30]
The image file is available in the media folder, yet it doesn't appear correctly in Obsidian. Could you investigate this problem? Thank you.

`![](file://media/59661686846628447.png)`

**Comment by Maboroshy** [comment]
Could you try changing `links_as_URI` option to `False` in the script file and report the result.
It should look like this:
```
## Select file link options
links_as_URI = False  # True for file://link%20target style links, False for /link target style links
```

**Comment by Maboroshy** [comment]
Closing since no feedback provided.
