### ISSUE TITLE
Only title instead of note

### ISSUE THREAD

**Issue by MrLagavulin** [Maboroshy/Note-Station-to-markdown#33]
The converted files only contain the title of the note, not the content.
NSX attached renamed as ZIP.
[20240331_144226_11102_Lagavulin.zip](https://github.com/Maboroshy/Note-Station-to-markdown/files/14815987/20240331_144226_11102_Lagavulin.zip)
 Thanks for having a look at this.

**Comment by Maboroshy** [comment]
I've got 8 notes after conversion. Each of them had content.

**Comment by MrLagavulin** [comment]
I'm using Kubuntu 22.04.

**Comment by MrLagavulin** [comment]
Which OS do you use? Probably I could test this in a VM.

**Comment by Maboroshy** [comment]
I'm currently on Windows 10. At the start the script was written and mostly tested on Manjaro Linux, but I've not tested it on Linux for a few years. I will also give it a go on Linux VM.

**Comment by MrLagavulin** [comment]
It worked for me on Windows 11. Thanks, I'm fine with it.

**Comment by Maboroshy** [comment]
I've dropped pandoc version check too early. Kubuntu 22.04 had the one too old for one for the options I've used. I've dropped the option to fix the issue.
