### ISSUE TITLE
Links are not retrieved

### ISSUE THREAD

**Issue by gxgoetz** [Maboroshy/Note-Station-to-markdown#35]
Hi and thanks for this very useful script. I managed to execute it however I realised that links embedded in single notes are not copied. By links I do not mean sth in the note itself - ie text you would originally write into the big pane - but the entry in the top right corner next to the keywords.
A solution to this would be excellent.

**Comment by Maboroshy** [comment]
Hi. Could you provide an .nsx file with such notes. I don't have a Synology box anymore.

**Comment by gxgoetz** [comment]
Thanks for replying. I would have to find out how to make this file. You'll hear from me!

**Comment by gxgoetz** [comment]
https://unicloud.uni-vechta.de/s/xAi5t7HAwTZBkbC

I hope this is working...

**Comment by Maboroshy** [comment]
Yes, I've got it. Looks like the link you need is the `brief` field of the note. I'll transfer it to yaml section.

**Comment by gxgoetz** [comment]
Thanks for getting back so quickly. 
It's hard to understand that Note Station creates this massive database and then not everything is in it. I mean where is it then?
Anyway I was hoping for a way and there doesn't seem to be one apart from copying every link manually into the main text pane.
Well.

**Comment by Maboroshy** [comment]
.nsx file is not the internal database the app uses. It's the export file which can have a different format and it's own limitations for compatibility reasons. There may be a way to get more from app's internal database. But my script doesn't go beyond .nsx 
 file's content.
