### ISSUE TITLE
Problems with import-tag-to-QON.qml

### ISSUE THREAD

**Issue by KraxelHuber** [Maboroshy/Note-Station-to-markdown#7]
I successfully installed the import-tag-to-QON.qml script. The script dialogue is telling me that the scripts seems to be valid.

However, if I click on an imported note, no tag will be created. The note starts with 

> Tags: tagName

![image](https://user-images.githubusercontent.com/29901736/48228666-220aa780-e3a6-11e8-83c7-9f67e1c16d96.png)

**Comment by Maboroshy** [comment]
I wrote a working import script, but today I've lost file system on my disk. Closing this issue will take a while.

**Comment by Maboroshy** [comment]
I've uploaded brand new script and rewrote readme. Please, test. 
The new script should import all notes at once.

**Comment by KraxelHuber** [comment]
It didn't work out 100% correct. Basically every tag has been created two times and my notes have been split across the same tags. That is, I do see a duplicate of every tag name, but under each individual tag name, different notes have been saved.

**Comment by Maboroshy** [comment]
Now that's interesting. I always thought that QON doesn't allow to create duplicate tags. I'll try to reproduce that.

**Comment by Maboroshy** [comment]
I have some good guess, why import script's didn't work. Please, test the new version I've uploaded.

**Comment by KraxelHuber** [comment]
Now it seems to work properly. Good job!

**Comment by KraxelHuber** [comment]
Maybe you now want to turn your attention towards Joplin? Joplin has a command line tool. Maybe it's possible to create some kind of script in order to link the attachments to the respective notes. Also, it may be possible to automatically tag the notes.
I could perform the beta test again ;-)
https://discourse.joplin.cozic.net/t/attaching-files-in-a-subfolder/1082
https://discourse.joplin.cozic.net/t/automatically-tagging-notes/1083

**Comment by Maboroshy** [comment]
Good that this issue is resolved. Thanks for testing.

I'm looking into what it takes to make Joplin import work. Not as easy as with QON for sure.
