### ISSUE TITLE
attachment_id in note_data.get('attachment', ''):

### ISSUE THREAD

**Issue by csss1234** [Maboroshy/Note-Station-to-markdown#9]
my first time using github or python, so go easy on me plz!  I'm getting this error everytime

File "nsx2md.py", line 130, in <module>
    for attachment_id in note_data.get('attachment', ''):

**Comment by Maboroshy** [comment]
I'll close this until there will be an error message I can work with.

**Comment by Maboroshy** [comment]
There was another issue about line 130 reported and resolved. You could test an updated script and check if your error is gone.
